<a href="https://colab.research.google.com/github/glaizalipato/student_success/blob/main/Capstone_Model_Provincial_Glaiza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Packages

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#Sklearn Imports

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

#Past Overall

In [ ]:
provincial_url = 'https://raw.githubusercontent.com/plthrs/FTW-CapstoneProject-TeamEagle/main/past_prov.csv?token=GHSAT0AAAAAAB6WHWXJD7BWRJHAMGYCQVY6Y73XORQ'
past_provincial = pd.read_csv(provincial_url, index_col=0)

In [ ]:
past_provincial.shape

(46, 20)

In [ ]:
past_provincial.columns

Index(['Graduated', 'HS_Avg_Grade_imputed_based_on_school_loc', 'HS_Private',
       'HS_Public', 'HS_SUCs/LUCs', 'Percent_of_Income_Cutoff', 'Class_Poor',
       'Class_Lower', 'Class_Lower_Middle', 'Class_Middle_Middle',
       'Class_Upper_Middle', 'Is_More_Urbanized_Location',
       'Is_Fam_Size_Below_Ave', 'School_Within_Municipality',
       'School_Outside_Municipality_but_Within_Province',
       'School_Outside_Province_but_Within_Region', 'School_Outside_Region',
       'Both_Parent_Unemployed', 'Only_One_Parent_Emmployed',
       'Both_Parent_Employed'],
      dtype='object')

In [ ]:
past_provincial.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 46 entries, 2015061.0 to 2020192.0
Data columns (total 20 columns):
 #   Column                                           Non-Null Count  Dtype  
---  ------                                           --------------  -----  
 0   Graduated                                        46 non-null     int64  
 1   HS_Avg_Grade_imputed_based_on_school_loc         46 non-null     float64
 2   HS_Private                                       46 non-null     int64  
 3   HS_Public                                        46 non-null     int64  
 4   HS_SUCs/LUCs                                     46 non-null     int64  
 5   Percent_of_Income_Cutoff                         46 non-null     float64
 6   Class_Poor                                       46 non-null     int64  
 7   Class_Lower                                      46 non-null     int64  
 8   Class_Lower_Middle                               46 non-null     int64  
 9   Class_Middle_Midd

#Trial 1

In [ ]:
X = past_provincial.drop('Graduated', axis=1)
y = past_provincial['Graduated']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state =1)

In [ ]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
predictions = logmodel.predict(X_test)

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.69      0.90      0.78        10

    accuracy                           0.64        14
   macro avg       0.35      0.45      0.39        14
weighted avg       0.49      0.64      0.56        14



In [ ]:
accuracy_score(y_test, predictions)

0.6428571428571429

In [ ]:
logmodel.coef_

array([[-0.29259367,  0.09305473, -0.04934593,  0.        , -0.08631871,
         0.0437088 ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.47912261, -0.01524564, -0.38361254,  0.27338177,  0.15393957,
         0.        ,  0.46570688,  0.296844  , -0.71884208]])

#Trial 2

In [ ]:
X = past_provincial[['HS_Avg_Grade_imputed_based_on_school_loc', 'HS_Private', 'Percent_of_Income_Cutoff','Is_More_Urbanized_Location',
       'Is_Fam_Size_Below_Ave',
       'School_Outside_Municipality_but_Within_Province',
       'Both_Parent_Employed']]
y = past_provincial['Graduated']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state =1)

In [ ]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

LogisticRegression()

In [ ]:
predictions = logmodel.predict(X_test)

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.71      1.00      0.83        10

    accuracy                           0.71        14
   macro avg       0.36      0.50      0.42        14
weighted avg       0.51      0.71      0.60        14



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
accuracy_score(y_test, predictions)

0.7142857142857143

In [ ]:
logmodel.coef_

array([[-0.29125609,  0.21654158, -0.07354343, -0.60206281, -0.06751827,
         0.349967  , -0.87570503]])

#Trial 3

https://towardsdatascience.com/feature-selection-using-logistic-regression-model-efc949569f58

In [ ]:
X = past_provincial.drop('Graduated', axis=1)
y = past_provincial['Graduated']

In [ ]:
# Standardize the train and test sample
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.30, random_state =1)

In [ ]:
# Perform GridSearchCV to tune best-fit LR model
param = {'C': [10**-2,10**-1,10**0,10**1,10**2]}

lr_model = LogisticRegression(penalty='l1', solver='liblinear')
gs_model = GridSearchCV(estimator=lr_model, param_grid=param)
gs_model.fit(X_train, y_train)

# Train a LR model with best parameters
model = LogisticRegression(**gs_model.best_params_, penalty='l1', solver='liblinear')
model.fit(X_train, y_train)

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [ ]:
model.coef_

array([[-0.46238291,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.31781098,  0.        , -0.13627023,  0.        ,  0.        ,
         0.        ,  0.15035474,  0.        , -0.48330044]])

#Trial 4

In [ ]:
X = past_provincial[['HS_Avg_Grade_imputed_based_on_school_loc',
       'Is_Fam_Size_Below_Ave',
       'School_Outside_Municipality_but_Within_Province',
       'Both_Parent_Unemployed',
       'Both_Parent_Employed']]
y = past_provincial['Graduated']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state =1)

In [ ]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
predictions = logmodel.predict(X_test)

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.71      1.00      0.83        10

    accuracy                           0.71        14
   macro avg       0.36      0.50      0.42        14
weighted avg       0.51      0.71      0.60        14



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
accuracy_score(y_test, predictions)

0.7142857142857143

In [ ]:
logmodel.coef_

array([[-0.26941563, -0.07539347,  0.54905824,  0.37593527, -0.89895687]])

#Trial 5

In [ ]:
X = past_provincial[['HS_Avg_Grade_imputed_based_on_school_loc',
       'Is_Fam_Size_Below_Ave',
       'School_Outside_Municipality_but_Within_Province',
       'Both_Parent_Employed']]
y = past_provincial['Graduated']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state =1)

In [ ]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

LogisticRegression()

In [ ]:
predictions = logmodel.predict(X_test)

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.71      1.00      0.83        10

    accuracy                           0.71        14
   macro avg       0.36      0.50      0.42        14
weighted avg       0.51      0.71      0.60        14



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
accuracy_score(y_test, predictions)

0.7142857142857143

In [ ]:
confusion_matrix(y_test, predictions)

array([[ 0,  4],
       [ 0, 10]])

In [ ]:
logmodel.coef_

array([[-0.28058236, -0.07173595,  0.54329678, -0.93013182]])

In [ ]:
logmodel.predict_proba(X_test)[:,1]

array([0.75864071, 0.90615544, 0.91375335, 0.78246804, 0.7677347 ,
       0.61174135, 0.86822154, 0.66232686, 0.87227657, 0.95993935,
       0.66232686, 0.8886072 , 0.92397681, 0.94522526])

In [ ]:
logmodel.classes_

array([0, 1])